trigger: 
- main 

jobs: 
- job: BuildAndTest
  workspace: 
    clean: all 
  pool: my-personal-computer
    
   
  steps: 
  - checkout: self
    fetchDepth: 0
  
  
  - task: gitversion/execute@0
    inputs:
      useConfigFile: true 
      targetPath: /home/lenovo/myagent/chabchoubhabib123/1/s

  - script: echo current version is $(GitVersion.SemVer) 
    displayName: 'Display calculated version' 
  - task: Bash@3 
    inputs: 
      targetType: inline 
      script: echo "##vso[build.updatebuildnumber]$(SemVer)" 
    displayName: 'Update build number'