trigger: 
- main 


variables:
   # Deployment location
  location: 'West Europe'
  # Artifact name
  artifactName: 'azure.linked-arm-templates' 
  

  


jobs: 
- job: BuildAndTest
  workspace: 
    clean: all 

  pool: my-personal-computer
  

  
  steps: 

  - checkout: self
    fetchDepth: 0
  
  
  
  - task: gitversion/execute@0
    inputs:
      useConfigFile: true 
      configFilePath: './GitVersion.yml'
  - script: echo current version is $(GitVersion.SemVer) 
    displayName: 'Display calculated version' 
  - task: Bash@3 
    inputs: 
      targetType: inline 
      script: echo "##vso[build.updatebuildnumber]$(SemVer)" 
    displayName: 'Update build number'
    
 
  - task: CopyFiles@2
    displayName: Copy files
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName:  Publish build artifacts
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(artifactName)'

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Create a resource group
    inputs:
        deploymentScope: 'Subscription'
        ConnectedServiceName: $(subscriptionName)
        subscriptionName: $(subscriptionId)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: '$(Agent.BuildDirectory)\$(artifactName)\resource-group\azuredeploy.json'
        csmParametersFile: '$(Agent.BuildDirectory)\$(artifactName)\resource-group\azuredeploy.parameters.json'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'armOutputs'
        
        
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: Create a storage account for deployment artifacts
    inputs:
        deploymentScope: 'Resource Group'
        ConnectedServiceName: $(subscriptionName)
        subscriptionName: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: '$(Agent.BuildDirectory)\$(artifactName)\storage-account-for-artifacts\azuredeploy.json'
        csmParametersFile: '$(Agent.BuildDirectory)\$(artifactName)\storage-account-for-artifacts\azuredeploy.parameters.json'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'armOutputs'
        
        
  - task: TerraformInstaller@0
    displayName: install Terraform 
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV1@0
    displayName: terraform init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/skip-step'
      backendServiceArm: '$(subscriptionName)'
      backendAzureRmResourceGroupName: '$(resourceGroupName)'
      backendAzureRmStorageAccountName: '$(storageAccount)'
      backendAzureRmContainerName: '$(container)'
      backendAzureRmKey: '$(tfstateFile)'

  - task: TerraformTaskV1@0
    displayName: terraform plan -out=tfplan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/skip-step'
      commandOptions: '-out=tfplan'
      # commandOptions: '-detailed-exitcode -out=tfplan'
      environmentServiceNameAzureRM: '$(subscriptionName)'