trigger: 
- main 

jobs: 
- job: BuildAndTest
  workspace: 
    clean: all 
  pool: my-personal-computer
    
   
  steps: 
  - checkout: self
    fetchDepth: 0
  - script: dotnet tool install -g GitVersion.Tool
    displayName: 'Install dotnet-gitversion'
  
  - task: gitversion/execute@0
    inputs:
      useConfigFile: true 
      configFilePath: './GitVersion.yml'
      executablesPath: '/home/lenovo/.dotnet/tools/dotnet-gitversion' # Replace with the actual path

  - script: echo current version is $(GitVersion.SemVer) 
    displayName: 'Display calculated version' 
  - task: Bash@3 
    inputs: 
      targetType: inline 
      script: echo "##vso[build.updatebuildnumber]$(SemVer)" 
    displayName: 'Update build number'